export interface CrmTacheLib {
    id?: string  ;
    etat?: number ;
    id_projet?: string  ;
    projet_nom?: string  ;
    projet_date_creation?: Date  ;
    projet_date_echeance?: Date;
    projet_description?: string;
    employe_nom?: string ;
    id_sprint?: string  ;
    sprint_nom?: string  ;
    sprint_date_debut?: Date;
    sprint_date_fin?: Date;
    sprint_statut?: number;
    sprint_active?: number;
    nom?: string;
    descTache?: string; 
    statut?: number;
    priorite?: number;
    temps_estime?: number;
    date_creation?: Date; 
    id_employe_assigne?: string;
    id_tache_parent?: string;
    progresDyn?: number;
    date_debutEnCours?: Date; 
    date_termineTache?: Date;
    temps_actuel_dyn?: number;
    permission?: string;
    chef_projet_nom?: string;
    client_nom?: string;
}
